
services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portafolio
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:key_placeholder
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: portafolio
      DB_USERNAME: root
      DB_PASSWORD: root

  database:
    image: mysql:8.0
    container_name: mysql-db-portafolio
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portafolio
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadminportafolio
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"

volumes:
  db_data:
